name: "Moobile-Simulator"

exports: "moobile-simulator.js"

web: "[mootools.net](http://mootools.net)"

description: "Moobile Simulator API"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

authors: "Jean-Philippe Dery (jeanphilippe.dery@gmail.com)"

sources:

  - "Source/Device/Device.js"
  - "Source/Device/Device.iOS.js"
  - "Source/Device/Device.iPad.js"
  - "Source/Device/Device.iPhone4.js"
  - "Source/Device/Device.iPhone5.js"
  - "Source/Device/Device.GalaxyS3.js"
  - "Source/Simulator/Simulator.js"
  - "Source/Animation/Animation.js"
  - "Source/Animation/Animation.List.js"
  - "Source/Event/Event.CSS3.js"